import { useEffect, useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { Modal } from '../components/Modal'
import { api } from '../lib/api'
import { useToast } from '../components/Toast'
import { Field, ProjectSelect, ErrorBox, MemoryFrame, PageHeading, Pager, formatTime, useMemory, useMemoryMutation, useMemoryStatus } from '../lib/memory'
import { MemoryJobCard } from './MemoryProcessing'

export function MemorySettings() { return <MemoryFrame setup><Settings /></MemoryFrame> }
function Settings() {
  const status = useMemoryStatus(), cache = useQueryClient(), toast = useToast()
  const connectors = useMemory<any[]>('list_connectors', {}, status.data?.ready === true)
  const [connectorForm, setConnectorForm] = useState<any>(null), [credentials, setCredentials] = useState<any>(null), [dbUrl, setDbUrl] = useState('')
  const [jobsOffset, setJobsOffset] = useState(0)
  const jobs = useMemory<any>('list_jobs', { limit: 20, offset: jobsOffset }, status.data?.ready === true)
  const sync = useMemoryMutation('sync_connector'), retry = useMemoryMutation('retry_job'), cancel = useMemoryMutation('cancel_job'), updateConnector = useMemoryMutation('save_connector')
  const repair = useMemoryMutation('repair_google', () => toast.success('Reparación encolada'))
  const [ai, setAI] = useState<any>(null)
  useEffect(() => { if (status.data?.ready && status.data.ai && !ai) setAI(status.data.ai) }, [status.data, ai])
  useEffect(() => { if (!status.data?.ready) return; const interval = setInterval(() => { void jobs.refetch(); void status.refetch() }, 5000); return () => clearInterval(interval) }, [jobs.refetch, status.data?.ready, status.refetch])
  const saveDatabase = useMutation({ mutationFn: () => api.put('/memory/database', { url: dbUrl }), onSuccess: () => { setDbUrl(''); void cache.invalidateQueries({ queryKey: ['memory-status'] }); toast.success('Base de memoria conectada') }, onError: e => toast.error('No se pudo conectar', e.message) })
  const saveAI = useMutation({ mutationFn: () => api.put('/memory/ai', ai), onSuccess: () => { void status.refetch(); toast.success('Procesamiento configurado') }, onError: e => toast.error('No se guardó', e.message) })
  const reprocess = useMemoryMutation('reprocess', () => toast.success('Procesamiento encolado')), dedupe = useMemoryMutation('dedupe_people', () => toast.success('Búsqueda de duplicados encolada'))
  const oauth = useMutation({ mutationFn: (id: string) => api.post<{ authorization_url: string }>(`/memory/connectors/${id}/google/start`), onSuccess: result => window.open(result.authorization_url, '_blank', 'noopener,noreferrer'), onError: e => toast.error('No se pudo iniciar Google', e.message) })
  const backup = useMemoryMutation<any>('export_backup', async result => {
    let file: Blob
    try { file = await api.download(result.download_url.replace(/^\/api/, '')) } catch { toast.error('El respaldo se creó, pero no pudo descargarse'); return }
    const url = URL.createObjectURL(file), link = document.createElement('a')
    link.href = url; link.download = `agenthub-memory-${result.id}.json`; link.click(); URL.revokeObjectURL(url)
  })
  const restore = useMutation({ mutationFn: (body: unknown) => api.post('/memory/restore', body), onSuccess: () => { void cache.invalidateQueries(); toast.success('Memoria restaurada') }, onError: e => toast.error('No se restauró', e.message) })
  const workerActive = status.data?.worker?.heartbeat && Date.now() - Date.parse(status.data.worker.heartbeat) < 60_000
  return <><PageHeading title="Fuentes y ajustes" description="Elegí qué incorporar, controlá el procesamiento y revisá la cobertura." />
    <section className="card memory-panel"><div className="spread"><h2>Almacenamiento local</h2><span className={`badge ${status.data?.ready ? 'badge-on' : 'badge-stale'}`}>{status.data?.ready ? 'Conectado' : 'Por configurar'}</span></div>
      <p>La memoria y sus originales se guardan en esta computadora. El hub reanuda la sincronización al iniciar sesión.</p>
      {!status.data?.ready && <div className="memory-callout"><p>{status.data?.detail}</p><p>En desarrollo, <code>npm run memory:up</code> prepara PostgreSQL con Docker o con una instalación local.</p></div>}
      <details><summary>Conectar una base PostgreSQL existente</summary><form className="memory-form" onSubmit={e => { e.preventDefault(); saveDatabase.mutate() }}><Field label="URL de la base local"><input type="password" autoComplete="off" value={dbUrl} onChange={e => setDbUrl(e.target.value)} placeholder="postgresql://usuario:contraseña@127.0.0.1:54329/agenthub_memory" required /></Field><ErrorBox error={saveDatabase.error} /><button className="btn" disabled={saveDatabase.isPending}>Conectar base</button></form></details>
      <div className="memory-meta"><span>Procesamiento en segundo plano: {workerActive ? 'activo' : 'esperando servicio'}</span><span>{status.data?.pending_jobs ?? 0} trabajos pendientes</span></div>
    </section>
    <section className="memory-section"><div className="spread"><h2>Fuentes conectadas</h2><button className="btn btn-primary" disabled={!status.data?.ready} onClick={() => setConnectorForm({ provider: 'google', name: '', config: {}, project_ids: [], enabled: false, interval_minutes: 30 })}>Agregar fuente</button></div><ErrorBox error={connectors.error} />
      <div className="memory-connector-grid">{connectors.data?.map(connector => <div key={connector.id} className="card memory-panel"><div className="spread"><span className={`memory-provider provider-${connector.provider}`}>{connector.provider === 'google' ? 'G' : connector.provider[0].toUpperCase()}</span><span className={`badge ${connector.enabled ? 'badge-on' : ''}`}>{connector.enabled ? 'Activa' : 'Pausada'}</span></div>
        <h3>{connector.name}</h3><p className="muted">{connector.provider === 'google' ? 'Calendar, Meet y documentos de Drive' : connector.provider}</p><p className="field-hint">Última sincronización: {connector.last_success_at ? formatTime(connector.last_success_at) : 'Todavía no se sincronizó'}</p>{connector.last_error && <p className="memory-inline-error">{connector.last_error}</p>}
        <div className="memory-button-wrap"><button className="btn btn-sm" onClick={() => setConnectorForm(connector)}>Configurar</button><button className="btn btn-sm" onClick={() => connector.provider === 'google' ? oauth.mutate(connector.id) : setCredentials(connector)}>{connector.provider === 'google' ? 'Conectar Google' : 'Credenciales'}</button>
          <button className="btn btn-sm" onClick={() => updateConnector.mutate({ id: connector.id, provider: connector.provider, name: connector.name, config: connector.config, project_ids: connector.project_ids, interval_minutes: connector.interval_minutes, enabled: !connector.enabled })}>{connector.enabled ? 'Pausar' : 'Activar'}</button>
          <button className="btn btn-primary btn-sm" disabled={!connector.enabled || sync.isPending} onClick={() => sync.mutate({ id: connector.id })}>Sincronizar</button>{connector.provider === 'google' && <button className="btn btn-sm" disabled={!connector.enabled || repair.isPending} onClick={() => repair.mutate({ id: connector.id })}>Actualizar hablantes y emails</button>}</div></div>)}</div>
      {!connectors.data?.length && <p className="memory-empty">Agregá Google para descubrir reuniones, o comenzá con una importación de archivo desde Explorar.</p>}
    </section>
    <section className="card memory-panel"><div className="spread"><h2>Acceso a Google</h2><span className="badge">{status.data?.google_client_configured ? 'Cliente configurado' : 'Pendiente'}</span></div>
      <p>Configurá un cliente OAuth de escritorio de Google y luego conectá cada cuenta desde su fuente. El acceso se solicita en el navegador.</p><p className="field-hint">APIs: Calendar, Meet, Drive, Docs y People. Para resolver emails, reconectá Google y autorizá la lectura de contactos y directorio. Las identidades sin email disponible quedan pendientes de revisión.</p>
      <code className="memory-code">{status.data?.google_redirect_url}</code><button className="btn" onClick={() => setCredentials({ id: 'google-client', provider: 'google-client', name: 'Cliente OAuth de Google' })}>Configurar cliente OAuth</button>
    </section>
    {ai && <section className="card memory-panel"><h2>Procesamiento y búsqueda</h2><p>Los embeddings permiten buscar por significado. La extracción genera propuestas con evidencia para revisar.</p>
      <form className="memory-form" onSubmit={e => { e.preventDefault(); saveAI.mutate() }}><div className="memory-form-grid"><Field label="Modelo de extracción"><select value={ai.extraction} onChange={e => setAI({ ...ai, extraction: e.target.value, extraction_model: e.target.value === 'deepseek' ? 'deepseek-flash' : e.target.value === 'ollama' ? '' : ai.extraction_model })}><option value="disabled">Sin extracción automática</option><option value="deepseek">DeepSeek por API</option><option value="ollama">Modelo local en Ollama</option></select></Field><Field label="Nombre del modelo"><input required value={ai.extraction_model} onChange={e => setAI({ ...ai, extraction_model: e.target.value })} /></Field></div>
        {ai.extraction === 'deepseek' && <div className="memory-callout"><p>DeepSeek recibirá los fragmentos que se procesen. Los datos guardados siguen en tu computadora.</p><label className="check"><input type="checkbox" checked={ai.remote_processing_enabled} onChange={e => setAI({ ...ai, remote_processing_enabled: e.target.checked })} />Permitir procesamiento con DeepSeek</label><button className="btn" type="button" onClick={() => setCredentials({ id: 'deepseek', provider: 'deepseek', name: 'DeepSeek' })}>{status.data?.deepseek_configured ? 'Cambiar clave' : 'Configurar clave'}</button></div>}
        <label className="check"><input type="checkbox" checked={ai.identity_auto_merge !== false} onChange={e => setAI({ ...ai, identity_auto_merge: e.target.checked })} />Unificar automáticamente hablantes y perfiles duplicados cuando la IA declara confianza alta</label>
        <p className="field-hint">Los perfiles con el mismo email verificado se unifican siempre. En confianza media sólo se unifica un nombre completo idéntico frente a una etiqueta de documento sin email; el resto, y todo lo que tenga señales en contra, queda como propuesta en Por revisar. Cada unificación se registra en el historial de la persona.</p>
        <label className="check"><input type="checkbox" checked={ai.embeddings_enabled} onChange={e => setAI({ ...ai, embeddings_enabled: e.target.checked })} />Habilitar embeddings locales</label>
        <div className="memory-form-grid"><Field label="Dirección local de Ollama"><input required value={ai.ollama_url} onChange={e => setAI({ ...ai, ollama_url: e.target.value })} /></Field><Field label="Modelo de embeddings"><input required value={ai.embedding_model} onChange={e => setAI({ ...ai, embedding_model: e.target.value })} /></Field></div><p className="field-hint">El modelo debe estar instalado en Ollama. Al cambiarlo, reprocesá las fuentes para generar el nuevo índice.</p>
        <ErrorBox error={saveAI.error} /><div className="memory-button-wrap"><button className="btn btn-primary" disabled={!status.data?.ready || saveAI.isPending}>Guardar configuración</button><button className="btn" type="button" disabled={!status.data?.ready || reprocess.isPending} onClick={() => reprocess.mutate({ force: true })}>Reprocesar fuentes importadas</button><button className="btn" type="button" disabled={!status.data?.ready || dedupe.isPending} onClick={() => dedupe.mutate({})}>Buscar personas duplicadas</button></div>
      </form>
    </section>}
    <section className="memory-section"><div className="spread"><h2>Actividad de sincronización</h2><Link className="btn" to="/memory/processing">Ver procesamiento de IA</Link><button className="btn btn-sm" onClick={() => void jobs.refetch()}>Actualizar</button></div><ErrorBox error={jobs.error} /><div className="memory-processing-list">{jobs.data?.items.map((job: any) => <MemoryJobCard key={job.id} job={job} onRetry={id => retry.mutate({id})} onCancel={id => cancel.mutate({id})} />)}{!jobs.data?.items.length && <p className="memory-empty">No hay trabajos registrados.</p>}</div>{jobs.data && <Pager total={jobs.data.total} offset={jobsOffset} limit={20} setOffset={setJobsOffset} />}</section>
    <section className="card memory-panel"><h2>Respaldos y restauración</h2><p>El respaldo incluye los originales y las relaciones. Las credenciales se configuran por separado. Para restaurar, la memoria de destino debe estar vacía.</p><button className="btn" disabled={!status.data?.ready || backup.isPending} onClick={() => backup.mutate({})}>Crear y descargar respaldo</button>
      <Field label="Restaurar respaldo en una memoria vacía"><input type="file" accept=".json" disabled={!status.data?.ready || restore.isPending} onChange={e => { const file = e.target.files?.[0]; if (file) void file.text().then(content => { try { restore.mutate(JSON.parse(content)) } catch { toast.error('El respaldo no es JSON válido') } }).catch(() => toast.error('No se pudo leer el respaldo')) }} /></Field><ErrorBox error={restore.error} /></section>
    {connectorForm && <ConnectorForm connector={connectorForm} onClose={() => setConnectorForm(null)} />}{credentials && <CredentialsForm target={credentials} onClose={() => setCredentials(null)} />}
  </>
}
function ConnectorForm({ connector, onClose }: { connector: any; onClose: () => void }) {
  const [provider, setProvider] = useState(connector.provider), [name, setName] = useState(connector.name), [config, setConfig] = useState<any>(connector.config)
  const [projects, setProjects] = useState<string[]>(connector.project_ids), [interval, setInterval] = useState(connector.interval_minutes)
  const save = useMemoryMutation('save_connector', onClose)
  const listField = (key: string, label: string, placeholder: string) => <Field label={label}><textarea rows={2} value={(config[key] ?? []).join('\n')} placeholder={placeholder} onChange={e => setConfig({ ...config, [key]: e.target.value.split(/[\n,]+/).map((v: string) => v.trim()).filter(Boolean) })} /></Field>
  return <Modal open title={connector.id ? 'Configurar fuente' : 'Nueva fuente'} onClose={onClose} width={720} busy={save.isPending}><form className="memory-form" onSubmit={e => { e.preventDefault(); save.mutate({ ...(connector.id ? { id: connector.id } : {}), provider, name, config, project_ids: projects, interval_minutes: interval, enabled: connector.enabled }) }}>
    <div className="memory-form-grid"><Field label="Proveedor"><select value={provider} disabled={!!connector.id} onChange={e => { setProvider(e.target.value); setConfig({}) }}>{['google','notion','slack','jira'].map(p => <option key={p}>{p}</option>)}</select></Field><Field label="Nombre de la fuente"><input required value={name} onChange={e => setName(e.target.value)} placeholder="Google del trabajo" /></Field></div>
    {provider === 'google' && <>{listField('calendars', 'Calendarios (un ID por línea)', 'primary')}{listField('folder_ids','Carpetas de Drive (IDs)', 'Opcional: carpeta con documentos históricos')}{listField('document_ids','Documentos de Google (IDs)', 'Opcional: IDs de documentos concretos')}
      <label className="check"><input type="checkbox" checked={config.calendar_enabled !== false} onChange={e => setConfig({ ...config, calendar_enabled: e.target.checked })} />Importar eventos de Calendar</label><label className="check"><input type="checkbox" checked={config.meet_enabled !== false} onChange={e => setConfig({ ...config, meet_enabled: e.target.checked })} />Importar transcripciones de Meet disponibles</label></>}
    {provider === 'notion' && <>{listField('page_ids','Páginas de Notion (IDs)', 'Vacío: páginas accesibles a la integración')}<p className="field-hint">La integración debe tener acceso a las páginas. Se recorren bloques anidados y páginas hijas.</p></>}
    {provider === 'slack' && <>{listField('channel_ids','Canales de Slack (IDs)', 'C0123456789')}<p className="field-hint">El token necesita acceso al historial, respuestas de hilos e información de usuarios de esos canales.</p></>}
    {provider === 'jira' && <><Field label="Sitio de Jira Cloud"><input type="url" required value={config.site_url ?? ''} placeholder="https://empresa.atlassian.net" onChange={e => setConfig({ ...config, site_url: e.target.value })} /></Field><Field label="Filtro de tareas (JQL)"><textarea required rows={3} value={config.jql ?? ''} placeholder="project = POC ORDER BY updated DESC" onChange={e => setConfig({ ...config, jql: e.target.value })} /></Field></>}
    {(provider === 'google' || provider === 'slack') && <Field label="Importar desde"><input type="date" value={config.since?.slice(0,10) ?? ''} onChange={e => { const next = { ...config }; if (e.target.value) next.since = `${e.target.value}T00:00:00Z`; else delete next.since; setConfig(next) }} /><span className="field-hint">Meet sólo ofrece las intervenciones recientes; el histórico depende de documentos conservados.</span></Field>}
    <ProjectSelect value={projects} onChange={setProjects} /><Field label="Revisar cambios cada (minutos)"><input type="number" min={5} max={1440} value={interval} onChange={e => setInterval(Number(e.target.value))} /></Field><p className="field-hint">Una fuente nueva queda pausada hasta que configures sus credenciales y la actives.</p><ErrorBox error={save.error} /><button className="btn btn-primary" disabled={save.isPending}>Guardar fuente</button>
  </form></Modal>
}
function CredentialsForm({ target, onClose }: { target: any; onClose: () => void }) {
  const [token, setToken] = useState(''), [clientId, setClientId] = useState(''), [email, setEmail] = useState(''), cache = useQueryClient()
  const save = useMutation({ mutationFn: () => api.put(`/memory/credentials/${target.id}`, target.provider === 'google-client' ? { client_id: clientId, ...(token ? { client_secret: token } : {}) } : target.provider === 'deepseek' ? { api_key: token } : { token, ...(email ? { email } : {}) }), onSuccess: () => { setToken(''); void cache.invalidateQueries({ queryKey: ['memory-status'] }); onClose() } })
  async function loadGoogle(file?: File) {
    if (!file) return
    try { const data = JSON.parse(await file.text()); const client = data.installed ?? data.web; if (client?.client_id) { setClientId(client.client_id); setToken(client.client_secret ?? '') } } catch { /* the editable inputs remain available */ }
  }
  return <Modal open title={`Conectar ${target.name}`} onClose={onClose} busy={save.isPending}><form className="memory-form" onSubmit={e => { e.preventDefault(); save.mutate() }}>
    {target.provider === 'google-client' && <><Field label="Archivo de cliente OAuth de Google"><input type="file" accept=".json" onChange={e => void loadGoogle(e.target.files?.[0])} /></Field><Field label="Client ID"><input required value={clientId} onChange={e => setClientId(e.target.value)} autoComplete="off" /></Field></>}
    {target.provider === 'jira' && <Field label="Email de Jira"><input type="email" required value={email} onChange={e => setEmail(e.target.value)} /></Field>}
    <Field label={target.provider === 'google-client' ? 'Client secret (si corresponde)' : 'API key o token'}><input type="password" required={target.provider !== 'google-client'} autoComplete="off" value={token} onChange={e => setToken(e.target.value)} /></Field><p className="field-hint">Se guarda en un archivo privado de esta computadora. No se incluye en respaldos ni se devuelve al leer la configuración.</p><ErrorBox error={save.error} /><button className="btn btn-primary" disabled={save.isPending}>Guardar credencial</button></form></Modal>
}
